add warning support for query exceed parser memory limit
Summary:
Currently, if parser_max_mem_size is specified and the parser use more memory than parser_max_mem_size, mysqld will emit an error.

add a variable to emit an warning instead of error if query exceed parser_max_mem_size limit

Differential Revision: D48816551

--------------------

Release Parser memory after each statement

Summary:
Customer query may contain a lot statements and currently mysql won't release these memory until last statement finished.

The change is to early release memory used by parser.
- before this change, parser memory is  released until last statement finished.
- after this change, parser memory is released after current statement finish execution.

Differential Revision: D48628098

--------------------

Pass actual format string instead of nullptr in (#1410)

Summary:
This fixes a GCC build error:

sql/sql_parse.cc:7909:17: error: too many arguments for format [-Werror=format-extra-args]
 7909 |                 static_cast<ulonglong>(thd->variables.parser_max_mem_size),

Pull Request resolved: https://github.com/facebook/mysql-5.6/pull/1410

Differential Revision: D52259057

fbshipit-source-id: 164921676f5be07db3c827da71044c3be8667c13