Adding ability to apply binlogs thru mysqlbinlog in multi-threaded mode
Summary:
Added a new flag in `mysqlbinlog` `--mta-workers=x` that tells
the server to spawn `x` dependency applier workers to apply
transactions. When `--mta-workers` is specified all events are printed
in their base64 representation so we can create log events out of them.

Differential Revision: D49466823

---------------------------------------------------------------------------

Cast enum into target type in a ternary operator (#1411)

Summary:
This fixes a GCC build error:

sql/rpl_replica.cc: In function ‘int slave_start_single_worker(Relay_log_info*, ulong)’: sql/rpl_replica.cc:7207:28: error: enumerated and non-enumerated type in conditional expression [-Werror=extra]
 7207 |             rli->is_fake() ? INFO_REPOSITORY_DUMMY : opt_rli_repository_id, i,
      |             ~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Pull Request resolved: https://github.com/facebook/mysql-5.6/pull/1411

Differential Revision: D52207263

fbshipit-source-id: 47d7f5c3bbf6ec6eb25247b728e354e60d29552a