[vector] implement ivf flat index
Summary:
- update faiss submodule to have the change that allows passing context object to inverted list iterator
- load centroids from a table using command service
- implement storage for ivf flat index

update-submodule: faiss

Differential Revision: D54084982

fbshipit-source-id: e1a4ef4ce124831cd0a2fe082cdd7a3899cc5ade

---------------------------------------------------------------------------------

vectordb fix user name used to load trained index

Summary:
- change the user name used to load trained index data
- current query won't work when allow_noncurrent_db_rw is off, add a step to explicitly select database

Differential Revision: D54837680

fbshipit-source-id: 39bdd52fa12e32b537badba9301db04690a8af66

---------------------------------------------------------------------------------

Use PRIu64 to printf-format an uint64_t value (#1439)

Summary:
This fixes, on macOS:

```
storage/rocksdb/rdb_cmd_srv_helper.cc:115:52: error: format specifies type 'unsigned long' but the argument has type 'uint64_t' (aka 'unsigned long long') [-Werror,-Wformat]
                    "expect one row, but got %lu", row_count);
                                             ~~~   ^~~~~~~~~
                                             %llu
```

At the same time add some includes for the used declarations.

Pull Request resolved: https://github.com/facebook/mysql-5.6/pull/1439

Differential Revision: D55019705

fbshipit-source-id: 19a7982a62ba172714734716b08000e8762ac649