Add partial index iterator
Summary:
This adds the partial index iterator. It is a special iterator that sorts groups from the primary key on the fly as needed, and if it exceeds a certain threshold, it will materialize the rows on the secondary key as well.

In order to protect against concurrent index updates and materialization, locks are taken on the group prefix on the secondary key. When updating an partial index, a shared lock on the group is held, and a read is performed to see if a SK write is necessary or not. The shared lock is held until transaction commit. When materializing a group, an exclusive lock on the group is held, in order to ensure that we don't miss any writes going to that group.

For point queries, the secondary key read is not found, we simply extract the primary key parts and read from the primary key. This means that point queries don't trigger materialization though.

Reviewed By: hermanlee

Differential Revision: D25933178

--------------------------------------------------------------------------------------------

Avoiding unnecessary reseeks in primary key iterator

Summary:
Doing full index scans is currently more expensive than it needs to be with partial indexes. The problem is that for every distinct group, we have to reseek our primary key iterator. However, in most cases, a reseek is not necessary, as the primary key iterator is already at the correct position.

The change here is to track in `m_iterator_pk_position` the current position of the iterator relative to the current prefix. When seeking to the next prefix, we check if we are already positioned correctly, and then skip the seek if possible.

Also, as a minor optimization, use std::vector instead of std::map. This makes allocating/deallocating memory much cheaper.

Reviewed By: george-reynya

Differential Revision: D30681736

--------------------------------------------------------------------------------------------

Fix flaky rocksdb.partial_index_stress MTR

Summary:
sometime rocksdb.partial_index_stress MTR fail especially under myrocks DD due
```
MySQLdb._exceptions.OperationalError: (1213, 'Deadlock found when trying to get lock; try restarting transaction (snapshot conflict)')
```

From https://dev.mysql.com/doc/refman/8.0/en/set-transaction.html, SET SESSION TRANSACTION doesn't apply to cur trx.

The fix is to commit Isolation change first to avoid snapshot conflict during first insert

Differential Revision: D50420444