Log Thrift requests to Perf Schema
Summary:
Add instrumentation to log thrift request from bypass rpc workflow to performance schema (specifically the "esms_by_all" table). The changes made include:
- adding a sysvar to control pfs logging (this is enabled by default)
- adding statement/digest instrumentation to Bypass RPC path
- computing the query's digest if the sysvar is enabled (needed to log to performance schema)

Differential Revision: D46087826

-------------------------------------------------------------------------------------

Do not define static variables in a header file (#1409)

Summary:
Since they are used only once, move them to their respective use locations. This fixes a GCC compilation error:

In file included from /home/laurynas/vilniusdb/fb-mysql/storage/rocksdb/rdb_nosql_digest.cc:1: /home/laurynas/vilniusdb/fb-mysql/storage/rocksdb/./rdb_nosql_digest.h:28:20: error: ‘myrocks::desc_tok’ defined but not used [-Werror=unused-variable]
   28 | static LEX_CSTRING desc_tok{STRING_WITH_LEN("DESC")};
      |                    ^~~~~~~~
/home/laurynas/vilniusdb/fb-mysql/storage/rocksdb/./rdb_nosql_digest.h:27:20: error: ‘myrocks::asc_tok’ defined but not used [-Werror=unused-variable]
   27 | static LEX_CSTRING asc_tok{STRING_WITH_LEN("ASC")};
      |                    ^~~~~~~
/home/laurynas/vilniusdb/fb-mysql/storage/rocksdb/./rdb_nosql_digest.h:26:20: error: ‘myrocks::limit_tok’ defined but not used [-Werror=unused-variable]
   26 | static LEX_CSTRING limit_tok{STRING_WITH_LEN("LIMIT")};
      |                    ^~~~~~~~~
/home/laurynas/vilniusdb/fb-mysql/storage/rocksdb/./rdb_nosql_digest.h:25:20: error: ‘myrocks::by_tok’ defined but not used [-Werror=unused-variable]
   25 | static LEX_CSTRING by_tok{STRING_WITH_LEN("BY")};
      |                    ^~~~~~
/home/laurynas/vilniusdb/fb-mysql/storage/rocksdb/./rdb_nosql_digest.h:24:20: error: ‘myrocks::order_tok’ defined but not used [-Werror=unused-variable]
   24 | static LEX_CSTRING order_tok{STRING_WITH_LEN("ORDER")};
      |                    ^~~~~~~~~
/home/laurynas/vilniusdb/fb-mysql/storage/rocksdb/./rdb_nosql_digest.h:23:20: error: ‘myrocks::index_tok’ defined but not used [-Werror=unused-variable]
   23 | static LEX_CSTRING index_tok{STRING_WITH_LEN("INDEX")};
      |                    ^~~~~~~~~
/home/laurynas/vilniusdb/fb-mysql/storage/rocksdb/./rdb_nosql_digest.h:22:20: error: ‘myrocks::force_tok’ defined but not used [-Werror=unused-variable]
   22 | static LEX_CSTRING force_tok{STRING_WITH_LEN("FORCE")};
      |                    ^~~~~~~~~
/home/laurynas/vilniusdb/fb-mysql/storage/rocksdb/./rdb_nosql_digest.h:21:20: error: ‘myrocks::where_tok’ defined but not used [-Werror=unused-variable]
   21 | static LEX_CSTRING where_tok{STRING_WITH_LEN("WHERE")};
      |                    ^~~~~~~~~
/home/laurynas/vilniusdb/fb-mysql/storage/rocksdb/./rdb_nosql_digest.h:20:20: error: ‘myrocks::from_tok’ defined but not used [-Werror=unused-variable]
   20 | static LEX_CSTRING from_tok{STRING_WITH_LEN("FROM")};
      |                    ^~~~~~~~
/home/laurynas/vilniusdb/fb-mysql/storage/rocksdb/./rdb_nosql_digest.h:19:20: error: ‘myrocks::select_tok’ defined but not used [-Werror=unused-variable]
   19 | static LEX_CSTRING select_tok{STRING_WITH_LEN("SELECT")};
      |                    ^~~~~~~~~~

Pull Request resolved: https://github.com/facebook/mysql-5.6/pull/1409

Differential Revision: D52259043

fbshipit-source-id: 42a062a3b9b110b800c19e6ee5c297ba6930f925

------------------------------------------------------------------------------------

[thrift] Fix bypass_pfs_logging test

Summary:
Fixed failing tests and other bugs that showed up while attempting to
reproduce the issue
- update digest from test results; this is likely from recording test
  results on an older iteration
- set `thrift_server_bypass` to ON in thrift_server test initialization
  (this is needed after D52489280 sets this to `OFF` by default)
- clean up state of `bypass_pfs_logging` sys var after tests

Differential Revision: D52523295

fbshipit-source-id: eb5a1f893d57528d387bb2d1221c55f585998f56