[bypass] fix rocksdb_rpl.bypass_rpc_hlc, add logging to test_bypass_rpc_plugin
Summary:
- in none raft env, setting 'hlc_ts' attribute is skipped by RUN_HOOK_STRICT, fixed this
- added logging to rpc test plugin to help troubleshoot

Differential Revision: D52575589

fbshipit-source-id: dfd6e3eb74694a289f21f1de7c4a355750a98fe9

-------------------------------------------------------------------------------------

Fix recent macOS build regression on test_bypass_rpc_plugin (#1419)

Summary:
Use `PRIu64` to format `uint64_t` values to fix:
```
plugin/test_bypass_rpc_plugin/test_bypass_rpc_plugin_info.cc:502:28: error: format specifies type 'unsigned long' but the argument has type 'uint64_t' (aka 'unsigned long long') [-Werror,-Wformat]
  501 |         "calling bypass_select with query '%s', hlc_lower_bound_ts %lu",
      |                                                                    ~~~
      |                                                                    %llu
  502 |         query_str.c_str(), hlc_lower_bound_ts);
      |                            ^~~~~~~~~~~~~~~~~~
include/mysql/components/services/log_builtins.h:838:66: note: expanded from macro 'LogPluginErrMsg'
  838 |       .message_quoted("Plugin " LOG_COMPONENT_TAG " reported", ##__VA_ARGS__)
      |                                                                  ^~~~~~~~~~~
```

Pull Request resolved: https://github.com/facebook/mysql-5.6/pull/1419

Differential Revision: D52681496

fbshipit-source-id: 38dafc4172c80eeb2513a213974930dbd1a5b540