Fix export of extra headers
Summary:
Fix extra headers for mysql plugins.
- Add missing headers
- Eliminate dependency on sql_class.h
- Eliminate dependency on libz through my_checksum.h

Reviewed By: hermanlee

Differential Revision: D32938828

------------------------------------------------------------------

Fix fbcode header export for plugins

Summary:
Remove non-existing header and add two new headers for successful plugin build.
D38137703 is for the fbcode plugin changes.

Reviewed By: hermanlee

Differential Revision: D38139077

------------------------------------------------------------------

expose more headers file for plugins

Summary: These new headers files supports table access services

Differential Revision: D40125357

------------------------------------------------------------------

Make my_checksum.h include headers it uses (#1418)

Summary:
This fixes, on Linux on ARM:
```
In file included from /home/laurynas/vilniusdb/fb-mysql/_build-debug-llvm-12/include/installed_headers.cc:2: /home/laurynas/vilniusdb/fb-mysql/include/my_checksum.h:94:5: error: call to function 'memcpy' that is neither visible in the template definition nor found by argument-dependent lookup
    memcpy(&pv, buf, sizeof(PT));
    ^
/home/laurynas/vilniusdb/fb-mysql/include/my_checksum.h:119:21: note: in instantiation of function template specialization 'mycrc32::PunnedCrc32<unsigned long>' requested here
    return mycrc32::PunnedCrc32<std::uint64_t>(crc, pos, length);
                    ^
/usr/include/string.h:43:14: note: 'memcpy' should be declared prior to the call site extern void *memcpy (void *__restrict __dest, const void *__restrict __src,
             ^
```
Pull Request resolved: https://github.com/facebook/mysql-5.6/pull/1418

Test Plan: CI

Differential Revision: D52609960

fbshipit-source-id: 9a91393496e0cb187b91d1b8da3f78c62933ffc6