Implement MyRocks DDSE handler & handlerton methods (#1333)
Summary:
Implement MyRocks DDSE handler & handlerton methods

- Make ha_rocksdb::get_se_private_id assign SE-specific table and index IDs for
  the DD tables. Ensure that the assigned IDs are used by the MyRocks DD, using
  a new handler method get_index_id_for_dd_key_def that looks up the MyRocks
  index ID for a DD table in the SE-specific MySQL DD metadata. Call it from
  create_key_defs for DD tables to get the pre-assigned index IDs in advance, as
  opposed to user tables where the index IDs are assigned later. Introduce
  Rdb_ddl_manager::update_next_dd_index_id method that writes to MyRocks DD the
  pre-assigned maximum DD index ID.
- Write the server version to MyRocks DD on newly created instances.
- Never use writebatch MyRocks implementation for DD transactions.
- Split out the bulk of Rdb_ddl_manager::init to a new private method populate,
  call it both from init and a new method reset_map, which is used to implement
  rocksdb_dict_cache_reset_tables_and_tablespaces handlerton method.
- Implement other handlerton methods: is_dict_readonly (always returning false),
  and dict_cache_reset as a no-op.
- Remove "simulate_dd_table" debug injection point and remove/disable its uses
  in the tests, because its functionality will be covered by the actual DD
  tables.
- Also remove "ddse_rocksdb" debug injection point for both the above reason and
  the fact that it involves a system table instead of a DD table.

Pull Request resolved: https://github.com/facebook/mysql-5.6/pull/1333

Differential Revision: D48872533

--------------------------------------------------------------------------------------

avoid memory leak during Rdb_ddl_manager::reset_map (#1375)

Summary:
These tbl_def pointers in m_ddl_map must be released before clear() during reset_map

Pull Request resolved: https://github.com/facebook/mysql-5.6/pull/1375

Test Plan: CI

Differential Revision: D50313208

--------------------------------------------------------------------------------------

Fix GCC compilation error in rocksdb_dict_recover (#1408)

Summary:
storage/rocksdb/rdb_native_dd.cc: In function ‘bool myrocks::rocksdb_dict_recover(dict_recovery_mode_t, uint)’:
storage/rocksdb/rdb_native_dd.cc:105:1: error: control reaches end of non-void function [-Werror=return-type]

Pull Request resolved: https://github.com/facebook/mysql-5.6/pull/1408

Differential Revision: D52207287

fbshipit-source-id: c91156d1681593967466f4afba5ee943cb492093