[raft] Persisting ingestion checkpoint on binlog rotation
Summary:
On rotation calling ingestion hooks to update checkpoint. Also
storing the latest checkpoint in the prev metadata event on top of the
file so we can always bootstrap it from the last binlog.

Differential Revision: D51775290

fbshipit-source-id: 0e7cb196cbf92b1d7e2caa547c87143a502ef729

----------------------------------------------------------------------------------------

Fix the second and third binlog.cc build failure on macOS (#1423)

Summary:
This fixes

sql/binlog.cc:6658:52: error: invalid operands to binary expression ('std::pair<int64_t, int64_t>' (aka 'pair<long long, long long>') and 'std::pair<long, long>' (aka 'pair<long, long>'))
        if (raft_rotate_info->ingestion_checkpoint != std::pair(-1L, -1L)) {
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ ^  ~~~~~~~~~~~~~~~~~~~

sql/binlog.cc:8841:30: error: invalid operands to binary expression ('std::pair<int64_t, int64_t>' (aka 'pair<long long, long long>') and 'std::pair<long, long>' (aka 'pair<long, long>'))
        if (param.checkpoint != std::pair(-1L, -1L)) {
            ~~~~~~~~~~~~~~~~ ^  ~~~~~~~~~~~~~~~~~~~

Pull Request resolved: https://github.com/facebook/mysql-5.6/pull/1423

Differential Revision: D53140914

fbshipit-source-id: d3e990a07ec98097292826085e8abdd70a1c77ce

----------------------------------------------------------------------------------------

Checking current_thd for nullptr before calling clear_raft_info()

Summary: #title

Differential Revision: D52530255

fbshipit-source-id: a8fd5460f52f2ed1045f4667f964d83e5b3eb9d1